### ISSUE TITLE
Cannot import module without creating a manifest

### ISSUE THREAD

**Issue by mmayfield1** [rodneyviana/ODSyncService#5] opened 2019-05-17 17:21 UTC
import-module OneDriveLib.dll fails with "Could no load file or assembly.... expected to contain a manifest. If I create a OneDriveLib.psd1 containing

 @{

	ModuleVersion="1.0"
	CmdletsToExport = @()
	VariablesToExport = '*'
	AliasesToExport = @()

}

I can import the module but Get-ODStatus is not available and get-module -ListAvailable returns no cmdlets. I have gotten it to report by change @() to Get-ODStatus but running the command still returns "not recognized as the name of a cmdlet, function," ......

**Comment by rodneyviana** [comment] 2019-05-17 20:16
Hi mmayfield1,

When you download an unsigned DLL from the Internet as it is the case, the module is blocked by the operating system. You need to right-click the module and check ‘Unblock’ or run the command:

Unblock-File -Path <path-to-the-module>

Let me know if it resolved the issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mmayfield1** [comment] 2019-05-20 14:57
Unblocking the file was one of the first things I tried.

**Comment by mmayfield1** [comment] 2019-05-20 15:12
![OneDriveLibError](https://user-images.githubusercontent.com/12780846/58032186-b2f5d480-7ae7-11e9-8827-731afc154aca.PNG)

**Comment by rodneyviana** [comment] 2019-05-20 17:49
Hi mmayfield,

Drop the .psd1

Run:
Unblock-File -Path .\OneDriveLib.dll # I know you did it, but just for good measure
Import-Module .\OneDriveLib.dll
Get-ODStatus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mmayfield1** [comment] 2019-05-20 22:08
![Capture](https://user-images.githubusercontent.com/12780846/58054882-a8f0c780-7b21-11e9-9092-a0ed69202cdc.PNG)

As I said, I can't even import the module with the psd1 (manifest) file

**Comment by rodneyviana** [comment] 2019-05-20 23:17
This image is corrupted (bad image). Run Get-FileHash to check the signature. Next time I login I will check the official hash and post again. Meanwhile you may want to try to download it again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rodneyviana** [comment] 2019-05-21 15:21
Hi mmayField1,

I believe I know why you are having the problem. The DLL was compiled to .NET 3.5 which is not installed by default on Windows 10. This may be the cause of the bad image. I recompiled to 4.5 and uploaded here: https://github.com/rodneyviana/ODSyncService/tree/master/Binaries/PowerShell

See if it works now.

**Comment by mmayfield1** [comment] 2019-05-21 23:35
> Hi mmayField1,
> 
> I believe I know why you are having the problem. The DLL was compiled to .NET 3.5 which is not installed by default on Windows 10. This may be the cause of the bad image. I recompiled to 4.5 and uploaded here: https://github.com/rodneyviana/ODSyncService/tree/master/Binaries/PowerShell
> 
> See if it works now.

I'll give it a shot. Pretty sure our Win 10 images have .net 3.5 in the image.

**Comment by mmayfield1** [comment] 2019-05-22 00:04
Same behavior.

**Comment by mmayfield1** [comment] 2019-05-22 16:56
The filehash I get for the 4.5 version is 
SHA256          FB61368E775BDB2BC09795F640D0E99DE36C614C709D68320A2E40D2BBAAC228

**Comment by rodneyviana** [comment] 2019-05-22 22:31
I got a different reading:

PS C:\temp> Get-FileHash .\OneDriveLib.dll

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          F22F235E496F7335CCFB93BF51F25CFA2F6B0532E45EE2B1E72BCCAF6904DFA2       C:\temp\OneDriveLib.dll

And I downloaded again to make sure it is what I uploaded. The same result.
This code reading directly from web also gave the same result:

$url = 'https://github.com/rodneyviana/ODSyncService/raw/master/Binaries/PowerShell/OneDriveLib.dll';
$Response = Invoke-WebRequest -Uri $url
$Stream = $Response.RawContentStream;
Get-FileHash -InputStream $Stream


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mmayfield1** [comment] 2019-05-23 02:10
So it must have been one of the security applications on my Windows box. I downloaded it from my Linux box and transferred it over. The download on the Linux box matched your filehash and powershell was able to load it without a manifest and get-odstatus worked. Thank you! Sorry for taking you time.

**Comment by bzyg7b** [comment] 2020-01-09 22:25
Weirdly getting the same issue, but tried on a Linux and Windows machine, getting a different file hash all together: _31CEFDC5B28E6C3A8701444ACD0C2C5981D405034024DD600DB751E69B3C13BF_

**Comment by rodneyviana** [comment] 2020-01-10 16:42
> Weirdly getting the same issue, but tried on a Linux and Windows machine, getting a different file hash all together: 31CEFDC5B28E6C3A8701444ACD0C2C5981D405034024DD600DB751E69B3C13BF

It will change will change with each new version. To check the current version, run this powershell script:
```
$url = 'https://github.com/rodneyviana/ODSyncService/raw/master/Binaries/PowerShell/OneDriveLib.dll';
$Response = Invoke-WebRequest -Uri $url
$Stream = $Response.RawContentStream;
Get-FileHash -InputStream $Stream
```

As of Jan 10, 2020, the value was:
```
Algorithm       Hash                                                                   Path                     
---------       ----                                                                   ----                     
SHA256          31CEFDC5B28E6C3A8701444ACD0C2C5981D405034024DD600DB751E69B3C13BF                                
```

Which matches yours. So, what is the problem you are seeing?

**Comment by bzyg7b** [comment] 2020-01-13 11:16
This works on my work machine but not on my home machine, must be something to do with my execution policy. 

Thanks for the reply, this can be re-closed as it all works.

**Closed** 2020-02-13 21:22 UTC
